// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0qxZR0Vb5yXfeaNwDlW0hshVF8XNxufg',
    appId: '1:1057362165596:web:26a6290e8909cb70550b99',
    messagingSenderId: '1057362165596',
    projectId: 'brunohsp-dnd-app',
    authDomain: 'brunohsp-dnd-app.firebaseapp.com',
    storageBucket: 'brunohsp-dnd-app.appspot.com',
    measurementId: 'G-BL1G7XEWKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0gjArlBViQvoOCvbkOv4rTVxXZymf5TI',
    appId: '1:1057362165596:android:f8030b8224f56b47550b99',
    messagingSenderId: '1057362165596',
    projectId: 'brunohsp-dnd-app',
    storageBucket: 'brunohsp-dnd-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr2ZVpeyqTAPQHIbfAAdM4sXPOHvtDRDs',
    appId: '1:1057362165596:ios:2cc186d6e70326f4550b99',
    messagingSenderId: '1057362165596',
    projectId: 'brunohsp-dnd-app',
    storageBucket: 'brunohsp-dnd-app.appspot.com',
    iosBundleId: 'com.example.brunohspApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr2ZVpeyqTAPQHIbfAAdM4sXPOHvtDRDs',
    appId: '1:1057362165596:ios:21ac42d8901f868f550b99',
    messagingSenderId: '1057362165596',
    projectId: 'brunohsp-dnd-app',
    storageBucket: 'brunohsp-dnd-app.appspot.com',
    iosBundleId: 'com.example.brunohspApp.RunnerTests',
  );
}
